name: Publish OpenAPI docs
on: [push]
jobs:
  deploy-openapi:
    name: Deploy OpenAPI
    runs-on: ubuntu-latest
    steps:

    # Any prerequisite steps
    - uses: actions/checkout@master

    # Deploy to local repo
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: openapi-docs
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}